language: python
python: "2.7.13"
  
# command to install dependencies
install: 
  - pip install .

#env variables
env:
  - RP_ENABLE_OLD_DEFINES=True RADICAL_PILOT_DBURL=mongodb://entk:entk@ds129013.mlab.com:29013/travis_tests

# command to run tests
script: python -m pytest -v /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/radical/entk/tests

# rabbitmq
services:
  - rabbitmq